### ISSUE TITLE
Return error code on failure.

### ISSUE THREAD

**Issue by mikebell** [zrrrzzt/html-validator-cli#1]
I'm trying to incorporate this tool into a build process but when run through npm test it doesn't return an error status code (1) so npm test thinks everything is fine.

If possible it would be great to provide the correct exit code so the tool can fail builds.

**Comment by zrrrzzt** [comment]
That would be possible, indeed :-)
I'll look into it tomorrow. If you're in a hurry just put together a PR

**Comment by mikebell** [comment]
Thanks! Will test this out tonight.

**Comment by radek-holy** [comment]
Can you please release a new version of the module? Thanks in advance.
