### ISSUE TITLE
Ignore errors

### ISSUE THREAD

**Issue by XhmikosR** [zrrrzzt/html-validator-cli#14]
Hi, there.

We've been using your html-validator module in BootstrapCDN. Now, we need to switch to html-validator-cli.

So, I'm wondering, is there any way to ignore specific errors like the html-validator module allows?

**Comment by zrrrzzt** [comment]
Hello :-)

How did you ignore the errors in the html-validator module?

If you need to see the full response from the validator to apply some extra logic you can run it with the ```--verbose``` flag.

Should you need anything else I can see what I can do, just let me know.

**Comment by XhmikosR** [comment]
We just filtered the messages like this  https://github.com/MaxCDN/bootstrap-cdn/blob/develop/tests/test_helper.js#L92

**Comment by zrrrzzt** [comment]
If you run the cli like this ```html-validator --file=<path-to-file> --format=text --verbose``` it will return the same result to stdin as you would in your example. Then you would have to pipe the result to a method for sorting/ignoring the errors. I do agree this is not a clean solution.

Regarding #3 there are existing modules for watching files in a folder and trigger commands and I will not implement similar functionality in this module.

**Comment by XhmikosR** [comment]
Allright, I'll see if I can filter the results. Is there any plan to add an `exclude` option in the near future?

About #3, perhaps I misunderstood, but what I'd like to see is scanning multiple files at once. For now I'll have to run the validator `x` times, where `x` is the number of pages. This is far from optimal especially for many files.

**Comment by zrrrzzt** [comment]
html-validator and html-validator-cli are just wrappers for the validator.w3.org/nu api. Given there are no support for exclude in the service itself it was never on my todo-list. The way you implemented this in your example could probably be copied quite easily so I'll look into anyway :-)

Give me a couple of days.

**Comment by zrrrzzt** [comment]
I've added support for ignore in [html-validator](https://github.com/zrrrzzt/html-validator) @XhmikosR 
Could you take a look at it? If this is a good enough solution for your usecase I'll add it to the cli as well.

**Comment by XhmikosR** [comment]
@zrrrzzt; thanks, I'll have a look as soon as possible.

/CC @jmervine, can you also check this out?

**Comment by jmervine** [comment]
@XhmikosR +1 Seems like a simple enough solution at a glance. I can run some tests with it later today, if you don't get to it first.

@zrrrzzt Thanks!

**Comment by zrrrzzt** [comment]
Updated cli just now to support ```--ignore=<string to ignore>```if you need to drop multiple strings just add more ```--ignore```

**Comment by XhmikosR** [comment]
Closing this since you have a fix now. Thanks!

**Comment by HouCoder** [comment]
I've noticed that the --ignore only ignores error message, it still shows the error code line number:

```
➜  demo git:(master) ✗ html-validator http://tonni.info/files/w3c-validator/  --verbose --ignore='Error: Bad value “” for attribute “src” on element “img”: Must be non-empty.' --validator='http://html5.validator.nu'
From line 8, column 5; to line 8, column 37
There were errors. (Tried in the text/html mode.)
```

Also, you see the `“src”` and `“img”` in the validation result, why it's not using the normal ANSI double quote mark `"`?

**Comment by zrrrzzt** [comment]
@HouCoder your use of ```--verbose``` kind of overrides the ```--ignore```

```
> html-validator http://tonni.info/files/w3c-validator/ --ignore='Error: Bad value “” for attribute “src” on element “img”: Must be non-empty.' --validator='http://html5.validator.nu'
Page is valid
```

Regarding the quotation marks it is what validator (http://html5.validator.nu) returns and not something I've added to this module.
