### ISSUE TITLE
Multiple files support

### ISSUE THREAD

**Issue by radek-holy** [zrrrzzt/html-validator-cli#3]
Hello,
I'd like to ask you to implement (and document) support for specifying multiple input files (without a need to prefix every file name with a command line option). That would allow us to run `html-validator-cli` from build (e.g. npm) scripts. There is actually a lot of linters that accept multiple files already.

**Comment by zrrrzzt** [comment]
Thank you for your interest in this module. This is a cli for [html-validator](https://github.com/zrrrzzt/html-validator) and the purpose of that module is validating a single page using [validator.w3.org/nu](https://validator.w3.org/nu/). I have no plans to add support for multiple input for any of these modules.
They are made to be included in other modules which can handle multiple files or other sources of input.

**Comment by radek-holy** [comment]
Fair enough

**Comment by XhmikosR** [comment]
@zrrrzzt: I still personally believe this is a valid request. Otherwise, if you have another solution with pure npm scripts let me know. I'm looking into switching to html-validator-cli for Bootstrap.
