### ISSUE TITLE
Resolve files through local machine

### ISSUE THREAD

**Issue by pattiereaves** [zrrrzzt/html-validator-cli#70]
I am looking for a solution to validating files in my local development environment. When I point to a local dev url, I get the message
```
IO Error: local.dev: Name or service not known
```
Is there a way I could solve this problem using this tool?

**Comment by zrrrzzt** [comment]
I can think of to different ways to use this in a local environment.

1. Set a variable of the rendered page and use the --data flag

```bash
DATA=$(curl http://local.dev) && html-validator --data=$DATA
```

2. Set up a tunnel to give the world access to you local environment while testing.
I've used [ngrok](https://ngrok.com) a couple of times but there are other alternatives as well.

Hope any of this is helping.
