### ISSUE TITLE
Crawl all pages in the same domain

### ISSUE THREAD

**Issue by p1ho** [zrrrzzt/html-validator-cli#91]
Hello,

First of all I'd like to say that this is a great tool! It just works.
However, it seems that this tool only evaluates 1 page at a time.
I was wondering if there are any plans to include a crawl option so it evaluates the entire site within the same domain? (i.e., give it the homepage, and it'll recurisvely crawl the links with relative hrefs or pages with the same domain)
There was a tool developed for this purpose on npm called [w3c-validator-cli](https://www.npmjs.com/package/w3c-validator-cli), but it's deprecated.

**Comment by zrrrzzt** [comment]
Thank you for your interest in this project.

The scope for the module is to be a simple wrapper for [validator.w3.org/nu/](https://validator.w3.org/nu/). To keep it simple and focused I will not implement a crawler. If you need the functionality you could probably make use of [sitemap-crawler](https://www.npmjs.com/package/sitemap-crawler) and [html-validator](https://www.npmjs.com/package/html-validator) and write something like this :-)

```JavaScript
(async () => {
  const siteMap = require('sitemap-crawler')
  const validate = require('html-validator')
  const url = 'http://www.npmjs.com'

  function generateSitemap (url) {
    return new Promise(async (resolve, reject) => {
      siteMap(url, (error, result) => {
        if (error) {
          return reject(error)
        } else {
          return resolve(result)
        }
      })
    })
  }

  function isValidHtml (result) {
    const errorMessages = result.messages ? result.messages.filter(message => message.type === 'error') : []
    return errorMessages.length === 0
  }

  let pagesToValidate = await generateSitemap(url)

  const validateNextPage = async () => {
    console.log(`Got ${pagesToValidate.length} pages left to check`)
    if (pagesToValidate.length > 0) {
      const pageUrl = pagesToValidate.pop()
      const testResult = await validate({ url: pageUrl })
      const resultJson = JSON.parse(testResult)
      console.log(JSON.stringify(resultJson, null, 2))
      if (isValidHtml(resultJson)) {
        await validateNextPage()
      } else {
        console.error(`${pageUrl} got errors`)
        console.log(JSON.stringify(resultJson, null, 2))
        process.exit(1)
      }
    } else {
      console.log('Finished')
    }
  }

  await validateNextPage()
})()
```

**Comment by p1ho** [comment]
Wow, thank you so much!! I haven't tested it, but this looks like it'll work!
Are you considering publishing another package that does this?

**Comment by zrrrzzt** [comment]
I don't think I'll publish it. But you can do it if you want to. You have most of the code so just add a `package.json` and some tests :-)

**Comment by p1ho** [comment]
Sure! I've never published a npm package before, but this'll be good practice.
I'll link to the PR and the npm page when I'm done, and I'll credit you wherever I can!
Please keep this thread open until then.
Thanks!

**Comment by zrrrzzt** [comment]
Cool! Here's the example as a gist https://gist.github.com/zrrrzzt/f0f2e5d64f2b69b330f377423717d7a7 and this is a guide for writing cli modules https://medium.com/netscape/a-guide-to-create-a-nodejs-command-line-package-c2166ad0452e

**Comment by p1ho** [comment]
Hello, I've created the repository for the module (**[site-validator-cli](https://github.com/p1ho/site-validator-cli.git)**) for the package here. I haven't uploaded it to npm because I'm still thinking about how to best write tests for it. I've also included you as a contributor on the repository (hopefully you have gotten an invite from me).

The readme is still TODO, but you can look at [getHelpText](https://github.com/p1ho/site-validator-cli/blob/master/lib/getHelpText.js) to see how to operate (I used yours as a template).

Because this is much heavier than what **html-validator-cli** does (especially the sitemap generation process), I've included an option to cache for a certain amount of time.

I ended up using a different package (**[sitemap-generator](https://www.npmjs.com/package/sitemap-generator)**) for the sitemap generation (instead of **[sitemap-crawler](https://www.npmjs.com/package/sitemap-crawler)**) because **sitemap-crawler** seems to only crawl the links from the page it was given, but not links from the page it links to (in other words, doesn't get links 2 jumps away)

There is still one challenge I was unable to fix. **[sitemap-generator](https://www.npmjs.com/package/sitemap-generator)** automatically writes to an XML file on the drive instead of storing it in memory, so if this package is run on a drive where read/write cycles are costly (like SSD), this can be undesirable. I wasn't able to find a package that does exactly what I want though.

**Comment by zrrrzzt** [comment]
This is awsm :-)

I've joined your repo and can look into it tomorrow evening. I suggest we move the conversation to your new repo. If you agree feel free to close this issue.

**Comment by p1ho** [comment]
Thanks! Closing!
