### ISSUE TITLE
Invalid URL shows site validated

### ISSUE THREAD

**Issue by p1ho** [zrrrzzt/html-validator-cli#93]
Hello, I found that entering certain invalid urls will still pass as valid as shown below
![image](https://user-images.githubusercontent.com/22629067/53111487-24cf7980-350b-11e9-8f4f-b1b48e4b30e2.png)

However, running the following code
```JavaScript
(async () => {
  const validator = require('html-validator')
  let data = await validator({url: 'http://asdf'})
  console.log(data)
})()
```
outputs
```
{"url":"http://asdf","messages":[{"type":"non-document-error","subType":"io","message":"asdf: No address associated with hostname"}]}
```
which means html-validator is functioning correctly.

I think there just needs to be a check that includes checking for non-document-error.
If needed, I can submit a PR, and link here.

**Comment by zrrrzzt** [comment]
What would be the best response to this from the module?

I'm leaning towards `Page not found` and exit with 1?

**Comment by p1ho** [comment]
If the page is found, then it's either "Page is valid" or "Page is not valid"
If page is not found, then "Page not found"
